let mapleader = " "

set nocompatible
filetype off

let s:editor_root=expand("$HOME/.vim")
let s:vim_bundle=s:editor_root . '/bundles.vim'
let s:nvim_bundle=s:editor_root . '/nvimrc.bundles.vim'

call plug#begin()

if filereadable(expand(s:vim_bundle))
  execute "source " . expand(s:vim_bundle)
endif

if has('nvim')
  if filereadable(expand(s:nvim_bundle))
    execute "source " . expand(s:nvim_bundle)
  endif
endif

call plug#end()

syntax on
filetype plugin indent on

for config in [ s:editor_root . '/config.vim' ]
  if filereadable(expand(config))
    execute "source " . expand(config)
  endif
endfor
