# Uncomment to debug slow performance
# set -x

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

export EDITOR="vim"

# Path to the bash it configuration
export BASH_IT="/Users/twhitney/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'

### Themes
export THEME_SHOW_CLOCK_CHAR=false
# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# UTF-8
export LC_ALL=en_US.utf-8
export LANG="$LC_ALL"

export JAVA_HOME=$(/usr/libexec/java_home)
export XDG_CONFIG_HOME=$HOME/.config

RBENV_ROOT=$HOME/.rbenv
PATH=$HOME/go/bin:$RBENV_ROOT/bin:$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH

# Load Rbenv
[ `which rbenv` ] && eval "$(rbenv init -)"

# Load direnv
[ `which direnv` ] && eval "$(direnv hook bash)"

tmux2host() {
  if [ $# -eq 2  ]; then
    user=$1
    host=$2
    ssh $1@$host -t "bash -l -c \"tmux new\""
  elif [ $# -eq 1 ]; then
    host=$1
    ssh $host -t "bash -l -c \"tmux new\""
  else
    echo 'Incorrect usage'
    echo "usage: tmux2host [user] host-ip"
    return 1
  fi
}

# The next line updates PATH for the Google Cloud SDK.
if [ -f /usr/local/opt/google-cloud-sdk/path.bash.inc ]; then
  source '/usr/local/opt/google-cloud-sdk/path.bash.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /usr/local/opt/google-cloud-sdk/completion.bash.inc ]; then
  source '/usr/local/opt/google-cloud-sdk/completion.bash.inc'
fi

source "$BASH_IT"/bash_it.sh
export PATH="$HOME/.cargo/bin:$PATH"
