#!/bin/sh

set -e
name="units/$1"

test "$name" || {
  echo "Usage: $0 name-of-unit"
  exit
}

mkdir -p "$name"
touch "$name/deps"
touch "$name/readme.md"
touch "$name/install.sh"
touch "$name/verify-install.sh"
