#!/usr/bin/env zsh
current_dir=$(cd "$(dirname "$0")" && pwd)

if [[ "$current_dir" != "$HOME/.dotfiles" ]]; then
  ln -sf "$current_dir" "$HOME/.dotfiles"
fi

if [[ ! -e "$current_dir/.last-update" ]]; then
  echo "LAST_EPOCH=18694" > "$current_dir/.last-update"
fi

set -e # Exit if any command fails

current_dir=$(cd "$(dirname $0)" && pwd)
pushd $current_dir
git submodule update --init --recursive

# Keep us from getting verify authenticity prompts from GitHub
mkdir -p $HOME/.ssh && chmod 0700 $HOME/.ssh
ssh-keyscan github.com >> ~/.ssh/known_hosts

# Install the priority units in the order they are listed
priority_units=`cat priority-units | grep -v '^#'`
./install-unit $priority_units

# Then install the rest of the units
all_units=`ls -d */ | grep -v '^_' | sed 's/\///'`
./install-unit $all_units
