#!/usr/bin/env zsh
set -e

if [[ $# -ne 1 ]]; then
  echo "must specify a host"
  echo "$0 host"
  exit 1
fi

host="$1"
current_dir=$(cd "$(dirname "$0")" && pwd)
host_path="$current_dir/hosts/$host.json"

if [[ ! -f "$host_path" ]]; then
  echo "host $host not found"
  exit 1
fi

source "$current_dir/lib.sh"

# jq is a required dependency
if [[ ! $(command -v jq) ]]; then
  temp=$(mktemp -d)
  curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o "${tmp}/jq"
  sudo mv "${tmp}/jq" /usr/local/bin/jq
  sudo chmod +x /usr/local/bin/jq
fi

# initialize last update with some time
if [[ ! -e "$$HOME/.config/dotfiles/last-update" ]]; then
  mkdir -p "$HOME/.config/dotfiles"
  echo "LAST_EPOCH=18694" > "$HOME/.config/dotfiles/last-update"
fi

set -e # Exit if any command fails

current_dir=$(cd "$(dirname $0)" && pwd)
pushd $current_dir > /dev/null

  # Keep us from getting verify authenticity prompts from GitHub
  update_github_ssh_keys

  ln -sf $host_path $HOME/.config/dotfiles/host.json

  # TODO: move priority-units into host file if needed
  # Insall the units
  pushd $current_dir
    ./install-unit $(cat "$host_path" | jq -r '.units | join(" ")')
    mkdir -p $HOME/.config/dotfiles/
  popd

popd
