cask_args appdir: "/Applications"

tap "caskroom/versions"

brew "aws-shell"
brew "awscli"
brew "cmake"
brew "direnv"
brew "dockutil"
brew "gawk"
brew "gettext", link: true
brew "git"
brew "htop"
brew "jq"
brew "lastpass-cli"
brew "pwgen"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby-install"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yarn", args: ["without-node"]

tap "git-duet/tap"
brew "git-duet"

cask "java"
brew "gradle"
brew "gradle-completion"

tap "caskroom/cask"
cask "atom"
cask "aquamacs"
cask "chromedriver"
cask "docker"
cask "firefox"
cask "flycut"
cask "google-cloud-sdk"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "slack"
cask "sublime-text"
cask "time-out"
cask "tunnelblick"
cask "xscreensaver"
cask "zoomus"

tap "universal-ctags/universal-ctags"
brew "universal-ctags"

#flyway needs to be after java
brew "flyway"

#these may or may not be installed depending on image
cask "shiftit" unless system "[ -d /Applications/ShiftIt.app/ ]"
cask "google-chrome" unless system "[ -d '/Applications/Google\ Chrome.app/' ]"
cask "jetbrains-toolbox" unless system "[ -d '/Applications/JetBrains\ Toolbox.app/' ]"
