foreground: &foreground "#3c3836"
background: &background "#f9f5d7"

blue: &blue "#458588"
cyan: &cyan "#689d6a"
green: &green "#98971a"
grey: &grey "#7c6f64"
lightGrey: &lightGrey "#928374"
magenta: &magenta "#b16286"
red: &red "#cc241d"
yellow: &yellow "#d79921"
orange: &orange "#d65d0e"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *yellow
  info:
    fgColor: *yellow
    sectionColor: *foreground
  frame:
    border:
      # XXX: Unused?
      fgColor: *red
      focusColor: *grey
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *background
      bgColor: *magenta
      activeColor: *yellow
    status:
      newColor: *yellow
      modifyColor: *orange
      addColor: *blue
      errorColor: *red
      highlightcolor: *blue
      killColor: *magenta
      completedColor: *lightGrey
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *yellow
      counterColor: *blue
      filterColor: *magenta
  views:
    # Charts skins...
    charts:
      bgColor: *red
      defaultDialColors:
        - linegreen
        - orangered
      defaultChartColors:
        - linegreen
        - orangered
    table:
      # XXX: Unused?
      # For some reason this is the border color in search mode
      fgColor: *red
      bgColor: *background
      # XXX: Unused?
      cursorColor: *red
      markColor: *magenta
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *yellow
    xray:
      fgColor: *red
      bgColor: *background
      cursorColor: *grey
      graphicColor: darkgoldenrod
      showIcons: false
    yaml:
      keyColor: *blue
      colonColor: *foreground
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *magenta
        bgColor: *background
