#!/usr/bin/env bash

open-in-vim() {
	local target="${PWD}"
	if [ -n "${1}" ]; then
		target=$(realpath "$1")
	fi

	local wdir="${target}"
	if [ -f "${target}" ]; then
		wdir=$(dirname "${target}")
	fi

	nohup alacritty --config-file ~/.config/alacritty/open-file.yml \
		--working-directory "${wdir}" \
		-t "nvim - ${target}" \
		-e "$SHELL" -lc "tmux -u new nvim \"${target}\"" >/dev/null &
}

open-in-vim "$@"
