# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="philips"

HYPHEN_INSENSITIVE="true"

plugins=(git ruby emacs vi-mode)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go@1.9/bin:$PATH"
source $HOME/.zprofile

autoload bashcompinit
bashcompinit
source $ZSH/oh-my-zsh.sh

if [ -d "$HOME/.bash_completion.d" ]; then
  for completion in `ls $HOME/.bash_completion.d`; do
    source "$HOME/.bash_completion.d/$completion"
  done
fi

# RPROMPT="hay"
# Stop zsh from autocompleting CD operations without typing cd
unsetopt AUTO_CD

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -d "$HOME/.bash_aliases.d" ]; then
  for alias in `ls $HOME/.bash_aliases.d`; do
    source "$HOME/.bash_aliases.d/$alias"
  done
fi

# This sets the characters that zsh understands as part of a word. Essentially,
# when you hit CTRL-w to delete a word, it will eat these characters too. Most
# importantly, the dash character. So with a path with dashes in it, you can
# use CTRL-w to remove the most recent directory, even if it has dashes! Bliss.
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Set Default Ruby
eval "$(rbenv init -)"
rbenv shell 2.4.1

# Fuzzy completion for history
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Direnv hook
eval "$(direnv hook zsh)"

export GROOVY_HOME=/usr/local/opt/groovy/libexec

export EDITOR=vim

bindkey -M viins 'jj' vi-cmd-mode

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

function zle-line-init zle-keymap-select {
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]% %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $(git_prompt_info) $EPS1"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

export KEYTIMEOUT=20
