# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="philips"

HYPHEN_INSENSITIVE="true"

plugins=(git ruby emacs)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go@1.9/bin:$PATH"
source $HOME/.zprofile

autoload bashcompinit
bashcompinit
source $ZSH/oh-my-zsh.sh

# RPROMPT="hay"
# Stop zsh from autocompleting CD operations without typing cd
unsetopt AUTO_CD

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# This sets the characters that zsh understands as part of a word. Essentially,
# when you hit CTRL-w to delete a word, it will eat these characters too. Most
# importantly, the dash character. So with a path with dashes in it, you can
# use CTRL-w to remove the most recent directory, even if it has dashes! Bliss.
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# Set Default Ruby
eval "$(rbenv init -)"
rbenv shell 2.4.1

# Fuzzy completion for history
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Direnv hook
eval "$(direnv hook zsh)"
