nerdfont: true
agent: opencode
worktree_dir: ../
worktree_naming: full
panes:
  - command: <agent>
    focus: true
post_create:
  - '[ ! -f .envrc ] && [ -f "$WM_PROJECT_ROOT/.envrc" ] && ln -s "$WM_PROJECT_ROOT/.envrc" .envrc || true'
  - direnv allow || true
